accounts/urls.py
from django.urls import path
from  . import views


app_name='accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register_page'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile_detail'),
    path('login/', views.LoginView.as_view(), name='login_page'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),
    path('following/<int:user_id>', views.userfollowingView.as_view(), name='following_page'),
    path('unfollowing/<int:user_id>', views.userunfollowingView.as_view(), name='unfollowing_page'),
    path('reset/', views.userpasswordresetView.as_view(), name='pass_reset'),
    path('reset/done', views.userpasswordresetdoneview.as_view(), name='pass_reset_done'),
    path('confirm/<uidb64>/<token>', views.userpasswordresetconfirmview.as_view(), name='pass_reset_confirm'),
    path('confirm/complete', views.userpasswordresetcompleteview.as_view(), name='pass_reset_complete'),
    
]

home/urls.py
from django.urls import path
from  . import views


app_name='home'

urlpatterns = [
    path('', views.mainpageView.as_view(), name='main_page'),
    path('createpost/', views.CreatpostView.as_view(), name='create_post'),
    path('postdetail/<int:post_id>', views.PostdetailView.as_view(), name='post_detail'),
    path('updatepost/<int:post_id>', views.updatepostView.as_view(), name='post_update'),
    path('reply/<int:post_id>/<int:comment_id>', views.replycommentView.as_view(), name='reply_page'),
    path('deletepost/<int:post_id>', views.deletpostView.as_view(), name='delete_post'),
    path('like/<int:post_id>/', views.postlikeView.as_view(), name='post_like')
    
]

mysocialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User





class Post(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='p_user')
    body=models.TextField()
    slug=models.SlugField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}_create_{self.slug}'
    
    def user_can_like(self, user):
        can_like=user.uvote.filter(post=self)
        if can_like.exists():
            return False
        return True






class Comment(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucom')
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcom')
    body=models.TextField(max_length=400)
    reply=models.ForeignKey('comment',on_delete=models.CASCADE, blank=True, null=True, related_name='recom')
    is_reply=models.BooleanField(default=False)
    created=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user}-comment-{self.body[:30]}__for__{self.post.body[:30]}'
    

class Vote(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE, related_name='uvote')
    post=models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvote')

    def __str__(self):
        return f'{self.user}--like --{self.post}'
    
 

home/forms.py
from django import forms
from .models import Post, Comment
from django.forms import ModelForm




class PostForm(forms.ModelForm):
    class Meta:
        model= Post
        fields=('body',)
        

class updatepostForm(forms.ModelForm):
    class Meta:
        model= Post
        fields=('body',)

class CommentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields=('body',)
        widgets={
            'body':forms.Textarea(attrs={'cols':30,'rows':5})
        }
        labels={
            'body':'your comment'
        }
    
class ReplyForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields=('body',)
        widgets={
            'body':forms.Textarea(attrs={'cols':30,'rows':2})
        }
        labels={
            'body':'reply'
        }
    

class postserachForm(forms.Form):
    search=forms.CharField()
        


        

home/views.py
from typing import Any
from django import http
from django.http.response import HttpResponse
from django.shortcuts import render,redirect, get_object_or_404,get_list_or_404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import PostForm, updatepostForm, CommentForm, ReplyForm, postserachForm
from .models import Post , Comment, Vote
from django.utils.text import slugify
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator





class mainpageView(View):
    form_class=postserachForm
    def get(self , request):
        posts=get_list_or_404(Post)
        if request.GET.get('search'):
            posts=Post.objects.filter(body__contains=request.GET['search'])
        return render(request, 'home/mainpage.html', {'posts':posts, 'form':self.form_class} )
    

class CreatpostView(LoginRequiredMixin, View):
    form_class= PostForm
    template_url='home/createpost.html'

    def get(self, request):
        return render(request,self.template_url,{'form':self.form_class})
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_post=form.save(commit=False)
            new_post.user=request.user
            new_post.slug=slugify(form.cleaned_data['body'][:30])
            new_post.save()
            messages.success(request, 'new post created','success')
            return redirect('home:main_page')
        messages.error(request, 'creating new post faild!','danger')
        return render(request,self.template_url, {'form':self.form_class,} )
    
class PostdetailView(View):
    form_class=CommentForm
    form_class_reply=ReplyForm
    def setup(self, request, *args: Any, **kwargs: Any):
        self.post_instance=Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    
    def get(self,request, *args, **kwargs):
        form=self.form_class
        comments=self.post_instance.pcom.filter(is_reply=False)
        can_like=False
        if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
            can_like=True
        return render(request, 'home/postdetail.html', {'post':self.post_instance, 'comments':comments, 'form' : form, 'replyform':self.form_class_reply, 'can_like':can_like})
    
    @method_decorator(login_required)
    def post(self, request,*args, **kwargs):
        form=self.form_class(request.POST)
        if form.is_valid():
            new_comment=form.save(commit=False)
            new_comment.user=request.user
            new_comment.post=self.post_instance
            new_comment.save()
            messages.success(request, 'you commented successfully','success')
            return redirect('home:post_detail', self.post_instance.id)
        messages.error(request,'faild', 'danger')
        return redirect('home:post_detail', self.post_instance.id)
    
class replycommentView(LoginRequiredMixin,View):
    form_class=ReplyForm
    def post(self,request, post_id, comment_id):
        post=get_object_or_404(Post,pk=post_id)
        Commentt=Comment.objects.get(pk=comment_id)
        form=self.form_class(request.POST)
        if form.is_valid():
            reply=form.save(commit=False)
            reply.user=request.user
            reply.post=post
            reply.reply=Commentt
            reply.is_reply=True
            reply.save()
            messages.success(request,'rply send sucessfully', 'success')
        return redirect('home:post_detail', post.id)


    


class updatepostView(LoginRequiredMixin, View):
    form_class=updatepostForm
    def setup(self, request, *args, **kwargs):
        self.post_instance=get_object_or_404(Post, id=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, ' you cant update this post', 'danger')
            return redirect('home:main_page')
        return super().dispatch(request, *args, **kwargs)
    

    def get(self, request, post_id):
        post=self.post_instance
        form=self.form_class(instance=post)
        return render(request, 'home/updatepost.html', {'form':form})

    def post(self, request, post_id):
        post=self.post_instance
        form=self.form_class(request.POST, instance=post)
        if form.is_valid():
            up_post=form.save(commit=False)
            up_post.slug=slugify(form.cleaned_data['body'][:30])
            up_post.save()
            messages.success(request, ' post  update sucessfully','success')
            return redirect('home:post_detail' , post.id)
        messages.error(request, 'update post faild!','danger')
        return redirect('home:post_detail', post.id)


class deletpostView(LoginRequiredMixin,View):
    def get(self,request, post_id):
        post=Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request,'post remove successfully', 'sucess')
        else:
            messages.error(request,'faild!', 'danger')
        return redirect('home:main_page')

    
class postlikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post=get_object_or_404(Post, pk=post_id)
        like=Vote.objects.filter(user=request.user, post=post)
        if like.exists():
            messages.error(request,'you liked this post already!', 'danger')
        else:
            Vote.objects.create(user=request.user, post=post)
            messages.success(request,'post liked successfully', 'sucess')
        return redirect('home:post_detail', post.id)




        

# Create your views here.

home/templates/home/createpost.html
{% extends 'base.html' %}
{% block content %}
<p>create new post</p>
<form action="", method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value="create">
</form>
{% endblock %}

home/templates/home/mainpage.html
{% extends 'base.html' %}
{% block content %}
<p class="text-center fs-1">wellcom to my page </p>
<form action="", method="get">
    {{form}}
    <input type="submit", value="find">
</form>
{% if request.user.is_authenticated %}
<h5>Hello {{ request.user.username }}</h5><br>
{% endif %}
{% for post in posts %}
<a href="{% url 'home:post_detail' post.id %}" , class="btn btn-secondary btn-sm">{{post.user.username}}--{{post.slug}}-----{{post.updated|timesince}}</a><br><br>
 {% endfor %}
{% endblock %}

home/templates/home/postdetail.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'accounts:profile_detail'  post.user.id %}">{{post.user.username}}</a>
<h2>{{ post.body }}</h2>
{% if request.user.is_authenticated %}
<a href="{% url 'home:post_like' post.id %}", class="{% if  not can_like %} disabled {% endif %} btn btn-primary ">like-{{post.pvote.count}}</a>
{% endif %}
{%  if request.user.id == post.user.id %}
    <a href="{% url 'home:post_update' post.id %}", class="btn btn-info">update post</a>
    <a href="{% url 'home:delete_post'  post.id %}", class="btn btn-info">delete</a>
{% endif %}




 

{% for comment in comments %}
    <div class="card-body bg-dark text-white m-2 p-2">
        <p >{{comment.body}}</p>
        <p>{{comment.user}}--{{comment.created|timesince}}</p><br>
        {% if request.user.is_authenticated %}
            <form action="{% url 'home:reply_page' post.id  comment.id %}", method="post">
            {% csrf_token %}
                {{replyform.as_p}}
                <input type="submit", value="send">
            </form>
        {% endif %}
        {% with replies=comment.recom.all %}
            {% for reply in replies %}
                <p>{{reply.body}}.....{{reply.user}}</p>
            {% endfor %}
        {% endwith %}
    </div>
        {% empty %}
            <p>no comment yet</p>
{% endfor %}
    



{% if request.user.is_authenticated %}
    <form action="", method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit", value="send">
    </form>
{% else %}
    <p>only loggedin user can send comment</p>
{% endif %}



{% endblock %}

home/templates/home/updatepost.html
{% extends 'base.html' %}
{% block content %}
<form action="", method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value="update">
</form>
{% endblock %}