accounts/urls.py
from django.urls import path
from  . import views


app_name='accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register_page'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile_detail'),
    path('login/', views.LoginView.as_view(), name='login_page'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),
    path('following/<int:user_id>', views.userfollowingView.as_view(), name='following_page'),
    path('unfollowing/<int:user_id>', views.userunfollowingView.as_view(), name='unfollowing_page'),
    path('reset/', views.userpasswordresetView.as_view(), name='pass_reset'),
    path('reset/done', views.userpasswordresetdoneview.as_view(), name='pass_reset_done'),
    path('confirm/<uidb64>/<token>', views.userpasswordresetconfirmview.as_view(), name='pass_reset_confirm'),
    path('confirm/complete', views.userpasswordresetcompleteview.as_view(), name='pass_reset_complete'),
    
]

home/urls.py
from django.urls import path
from  . import views


app_name='home'

urlpatterns = [
    path('', views.mainpageView.as_view(), name='main_page'),
    path('createpost/', views.CreatpostView.as_view(), name='create_post'),
    path('postdetail/<int:post_id>', views.PostdetailView.as_view(), name='post_detail'),
    path('updatepost/<int:post_id>', views.updatepostView.as_view(), name='post_update'),
    path('reply/<int:post_id>/<int:comment_id>', views.replycommentView.as_view(), name='reply_page'),
    path('deletepost/<int:post_id>', views.deletpostView.as_view(), name='delete_post'),
    path('like/<int:post_id>/', views.postlikeView.as_view(), name='post_like')
    
]

mysocialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User




class relation(models.Model):
    from_user=models.ForeignKey(User, on_delete=models.CASCADE, related_name='follower')
    to_user=models.ForeignKey(User,on_delete=models.CASCADE, related_name='following')
    connectedtime=models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.from_user} follow {self.to_user}'
    


class userprofile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    age=models.PositiveSmallIntegerField(default=0)
    bio=models.TextField(null=True, blank=True)

# Create your models here.

accounts/forms.py
from typing import Any
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError



class RegisterForm(forms.Form):
    username=forms.CharField(label='Enter Username',widget=forms.TextInput(attrs={'class':'form-control'}))
    email=forms.EmailField(label='Enter valid email',  widget=forms.EmailInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='Enter password',  widget=forms.PasswordInput(attrs={'class':'form-control'}))
    re_password=forms.CharField(label='Enter confirm password',  widget=forms.PasswordInput(attrs={'class':'form-control'}))
 
    def clean(self):
       cd= super().clean()
       p1=cd.get('password')
       p2=cd.get('re_password')
       if p1 and p2 and p1 != p2:
           raise ValidationError('passwords must match ')
       
    def clean_username(self):
        username=self.cleaned_data['username']
        user=User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('this username already exist! try another one')
        return username
    
    def clean_email(self):
        email=self.cleaned_data['email']
        user=User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exist! try another one')
        return email
    




class LoginForm(forms.Form):
    username=forms.CharField(label='Enter Username',widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(label='Enter password',  widget=forms.PasswordInput(attrs={'class':'form-control'}))

accounts/views.py
from typing import Any
from django import http
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.models import User
from django.views import View
from .forms import RegisterForm, LoginForm
from .models import relation
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login ,logout, authenticate
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy




class RegisterView(View):
    form_class=RegisterForm
    def get(self, request):
        form=self.form_class()
        return render(request, 'accounts/register.html', {'form':form})

        
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            User.objects.create_user(cd['username'], cd['email'], cd['password'])
            messages.success(request, 'you register successfully','success')
            return redirect('home:main_page')
        messages.error(request , 'registration field!!!', 'danger')
        return render(request, 'accounts/register.html', {'form':form})




    


class LoginView(View):
    form_class=LoginForm
    
    def setup(self, request, *args, **kwargs):
        self.next=request.GET.get('next')
        return super().setup(request, *args, **kwargs)
   
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:main_page')
        return super().dispatch(request, *args, **kwargs)
    

    def get(self, request):
        form=self.form_class()
        return render(request, 'accounts/login.html', {'form':form})
    
    def post(self, request):
        form=self.form_class(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user=authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request,'you login seccessfully', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:main_page')
            messages.error(request, 'username or password is wrong!','danger')
        return render(request, 'accounts/login.html', {'form':form})
    

class ProfileView(LoginRequiredMixin,View):
    def get(self, request, user_id):
        is_followed=False
        user= get_object_or_404(User, pk=user_id)
        posts=user.p_user.all()
        if relation.objects.filter(from_user=request.user, to_user=user). exists():
            is_followed=True
        return render(request,'accounts/profiledetail.html', {'user':user, 'posts':posts,'is_followed':is_followed})
        
class LogoutView(LoginRequiredMixin,View):
    def get(self, request):
       logout(request)
       messages.success(request,'you logout seccessfully', 'success')
       return redirect('home:main_page')
            

class userfollowingView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user=get_object_or_404(User, id= user_id)
        Relation=relation.objects.filter(from_user=request.user, to_user=user).exists()
        if Relation:
            messages.error(request, ' you already follow this user', 'danger')
        else:
            relation.objects.create(from_user=request.user, to_user=user)
            messages.success(request,'you follow seccessfully', 'success')
        return redirect('home:main_page')

class userunfollowingView(LoginRequiredMixin, View):
    def get(self , request, user_id):
        user=get_object_or_404(User, id=user_id)
        Relation=relation.objects.filter(from_user=request.user, to_user=user)
        if Relation.exists():
            Relation.delete()
            messages.success(request,'you unfollow seccessfully', 'success')
        else:
             messages.error(request, ' you not follow already', 'danger')
        return redirect('home:main_page')
    


# connecting google 



class userpasswordresetView(auth_views.PasswordResetView):
    template_name='accounts/pass_reset_form.html'
    success_url=reverse_lazy('accounts:pass_reset_done')
    email_template_name='accounts/pass_reset_email.html'


class userpasswordresetdoneview(auth_views.PasswordResetDoneView):
    template_name='accounts/pass_reset_done.html'


class userpasswordresetconfirmview(auth_views.PasswordResetConfirmView):
    template_name='accounts/pass_reset_confirm.html'
    success_url=reverse_lazy('accounts:pass_reset_complete')


class userpasswordresetcompleteview(auth_views.PasswordResetCompleteView):
    template_name='accounts/pass_reset_complete.html'



            









# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    <form action="" , method="post", class="col-md-5">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit", value="login",  class="btn btn-primary btn-sm">
    </form>
    <a href="{% url 'accounts:pass_reset' %}">forget your password? reset here</a>
{% endblock %}

accounts/templates/accounts/pass_reset_complete.html
{% extends 'base.html' %}
{% block content %}
<p>your password changed</p>

{% endblock %}

accounts/templates/accounts/pass_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
{% if validlink %}
<form action="", method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit", value="reset">
</form>
{% else %}
<p>this link is not valid! </p>
{% endif %}

{% endblock %}

accounts/templates/accounts/pass_reset_done.html
{% extends 'base.html' %}
{% block content %}
<p>we send you an email</p>

{% endblock %}

accounts/templates/accounts/pass_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:pass_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/pass_reset_form.html
{% extends 'base.html' %}
{% block content %}
<form action="", method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit", value="reset">
</form>
{% endblock %}

accounts/templates/accounts/profiledetail.html
{% extends 'base.html' %}
{% block content %}

    <p class="text-center  fs-1 ">{{ user.username|upper }}</p>
   {% if request.user.id == user.id %}
    <a href="", class="btn btn-info">Edit Profile</a>
    <a href="{% url 'accounts:logout_page' %} ", class="btn btn-info">Log Out</a>
    <a href="{% url 'home:create_post' %}", class="btn btn-info">create new post</a><br>
    {% endif %}
    {% if request.user.id != user.id  and not is_followed  %}
    <a href="{% url 'accounts:following_page' user.id %}", class="btn btn-secondary">follow</a>
    {% elif request.user.id != user.id and is_followed   %}
    <a href="{% url 'accounts:unfollowing_page' user.id %}", class="btn btn-secondary">unfollow</a>
    {% endif %}





    {% for post in posts %}
    <a href="{% url 'home:post_detail' post.id %}" , class="btn btn-secondary btn-sm">{{post.slug}}---{{post.created}}</a><br>
    {% endfor%}
    

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<form action="" , method="post", class="col-md-5">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit", value="register",  class="btn btn-secondary btn-sm">
</form>
{% endblock %}