accounts/urls.py
from django.urls import path
from  . import views


app_name='accounts'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register_page'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile_detail'),
    path('login/', views.LoginView.as_view(), name='login_page'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),
    path('following/<int:user_id>', views.userfollowingView.as_view(), name='following_page'),
    path('unfollowing/<int:user_id>', views.userunfollowingView.as_view(), name='unfollowing_page'),
    path('reset/', views.userpasswordresetView.as_view(), name='pass_reset'),
    path('reset/done', views.userpasswordresetdoneview.as_view(), name='pass_reset_done'),
    path('confirm/<uidb64>/<token>', views.userpasswordresetconfirmview.as_view(), name='pass_reset_confirm'),
    path('confirm/complete', views.userpasswordresetcompleteview.as_view(), name='pass_reset_complete'),
    
]

home/urls.py
from django.urls import path
from  . import views


app_name='home'

urlpatterns = [
    path('', views.mainpageView.as_view(), name='main_page'),
    path('createpost/', views.CreatpostView.as_view(), name='create_post'),
    path('postdetail/<int:post_id>', views.PostdetailView.as_view(), name='post_detail'),
    path('updatepost/<int:post_id>', views.updatepostView.as_view(), name='post_update'),
    path('reply/<int:post_id>/<int:comment_id>', views.replycommentView.as_view(), name='reply_page'),
    path('deletepost/<int:post_id>', views.deletpostView.as_view(), name='delete_post'),
    path('like/<int:post_id>/', views.postlikeView.as_view(), name='post_like')
    
]

mysocialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

templates/inc/messages.html
{% if messages %}
{% for msg in messages %}
    <p class="alert alert-{{ msg.tags }}" >{{ msg }}</p>
{% endfor %}






{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:main_page'%}">home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:profile_detail' request.user.id  %}">profile</a>
          </li>
        </ul>
      </div>
      {% else %}
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'accounts:register_page'%}">register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login_page' %}">login</a>
          </li>
        </ul>
      </div>
      {% endif %}
    </div>
  </nav>